name: Build TWRP for Xiaomi Pad 5 (Nabu)

on:
  workflow_dispatch:

env:
  # TWRP 官方核心源码（12.1分支目前完美兼容 A12-A15 的底层解密）
  MANIFEST_URL: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git'
  MANIFEST_BRANCH: 'twrp-12.1'
  
  # 自动指向设备树仓库和当前分支
  DEVICE_TREE_URL: 'https://github.com/goodmorningwsad-afk/device_xiaomi_nabu-recovery'
  DEVICE_TREE_BRANCH: 'android-12.1'
  
  # 物理坐标配置
  DEVICE_PATH: 'device/xiaomi/nabu'
  DEVICE_NAME: 'nabu'
  MAKEFILE_NAME: 'twrp_nabu'
  
  # Nabu 是 A/B 分区，没有独立 recovery 分区，所以必须打包成 bootimage
  BUILD_TARGET: 'bootimage'

jobs:
  build:
    name: Build TWRP
    # 🚨 物理环境替换：宿主机用最新，内部套 20.04 绝对隔离容器
    runs-on: ubuntu-latest
    container: ubuntu:focal
    permissions:
      contents: write

    steps:
    - name: ⏰ 检出代码
      uses: actions/checkout@v4

    - name: ⚙️ 配置极客编译环境 (粉碎 tzdata 交互卡点)
      run: |
        # 🚨 物理降维打击：声明非交互模式，强行设定默认时区为 UTC，彻底干掉弹窗！
        export DEBIAN_FRONTEND=noninteractive
        export TZ=Etc/UTC
        
        apt-get update
        apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq bc ccache sudo

    - name: 🌳 初始化 TWRP 核心源码树
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        repo init --depth=1 -u ${{ env.MANIFEST_URL }} -b ${{ env.MANIFEST_BRANCH }}
        repo sync -j$(nproc --all) --force-sync

    - name: 🌿 注入 Nabu 设备树
      run: |
        cd workspace
        git clone -b ${{ env.DEVICE_TREE_BRANCH }} ${{ env.DEVICE_TREE_URL }} ${{ env.DEVICE_PATH }}

    - name: 🚀 编译！
      run: |
        cd workspace
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ env.MAKEFILE_NAME }}-eng
        mka ${{ env.BUILD_TARGET }} -j$(nproc --all)

    - name: 📤 提取并上传 (修正真实物理产物名称)
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Recovery-Nabu
        path: workspace/out/target/product/${{ env.DEVICE_NAME }}/boot.img
